name: Continuous Integration

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get the flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=show --set-exit-if-changed .
        continue-on-error: true

      - name: Analyze project source
        run: flutter analyze --fatal-info
        continue-on-error: true

      - name: Run tests
        run: flutter test
        continue-on-error: true

