
name: Continuous Integration

on:
  push:
    branches: [ "main", "develop", "obnitram" ]
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get the flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        id: formatting
        continue-on-error: true
        run: |
          dart format --set-exit-if-changed .
          echo "formatting-outcome=$?" >> $GITHUB_ENV

      - name: Analyze project source
        id: analyze
        continue-on-error: true
        run: |
          flutter analyze --fatal-infos
          echo "analyze-outcome=$?" >> $GITHUB_ENV

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          flutter test
          echo "test-outcome=$?" >> $GITHUB_ENV

      - name: Generate Report
        id: report
        run: |
          echo "Report:"
          echo "Formatting Outcome: ${{ env.formatting-outcome }}"
          echo "Analyze Outcome: ${{ env.analyze-outcome }}"
          echo "Test Outcome: ${{ env.test-outcome }}"
          if [ ${{ env.formatting-outcome }} != 0 ] || [ ${{ env.analyze-outcome }} != 0 ] || [ ${{ env.test-outcome }} != 0 ]; then
            exit 1
          fi

